### ISSUE TITLE
where is DAv protocol is used

### ISSUE THREAD

**Issue by navinthenapster** [DAVFoundation/captain-n3m0#15]
The given code contains my sql database for data transfer, where is the testnet in ethereum is used. Can someone explain me how DAV protocol is used ?

**Comment by navinthenapster** [comment]
by the communication protocol , the shell command is given belong 
where is the server hosted and what is the discovery_endpoint ?
curl "discovery_endpoint_here" \
  --data "{ \
    \"start_at\": \"1513005534000\", \
    \"latitude\": \"32.787793\", \
    \"longitude\": \"-79.935005\", \
    \"radius\": \"2000\", \
    \"plug_type\": \"bullet_2mm\", \
  }"

**Comment by TalAter** [comment]
The communication protocol you are referring to is a bit outdated. We are releasing a new version of the network and SDK very soon and will be working on detailed documentation as well.
