### ISSUE TITLE
Add license badge to README (first-timers-only)

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/captain-n3m0#4]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for helping make drones fly, cars find charging stations, and people and goods get from place to place.

Find more **first-timers-only** issues [here](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+label%3A%22good+first+issue%22+user%3ADAVFoundation+).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, boats, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Captain n3m0

The DAV project you are looking at is *Captain n3m0*. It is a connector between the autonomous boat developed at California Maritime University and the DAV network. The goal of this boat is to help the autonomous boat find charging services, and thus allowing it to stay operational for longer times without human intervention, collecting scientific data for the university.

![n3m0_sailing](https://user-images.githubusercontent.com/926653/44045769-405c4404-9f32-11e8-86d1-a3e15f08e35b.gif)

![n3m0_open](https://user-images.githubusercontent.com/926653/44045787-52de3786-9f32-11e8-9e1b-5773b7abc7ea.jpg)

## How you can help

This project is licensed under the permissive open source MIT license.

Please edit the `README.md` file in the root directory of the repository to contain a link to our license file so that people know they are encouraged to contribute, fork, and extend this code.

The link should be placed just below the top headline. This is the markdown code required to display the link:

````markdown
[![license](https://img.shields.io/github/license/DAVFoundation/captain-n3m0.svg?style=flat-square)](https://github.com/DAVFoundation/captain-n3m0/blob/master/LICENSE)
````

This will look like this:

[![license](https://img.shields.io/github/license/DAVFoundation/captain-n3m0.svg?style=flat-square)](https://github.com/DAVFoundation/captain-n3m0/blob/master/LICENSE)

### Contributing to Captain n3m0

- [ ] Make sure this issue is labeled up-for-grabs and not labeled claimed, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Captain n3m0 GitHub page](https://github.com/DAVFoundation/captain-n3m0) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/captain-n3m0.git`
- [ ] **Add the file**
- [ ] Commit your changes and push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/captain-n3m0](https://github.com/YOUR-USER-NAME/captain-n3m0)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#1`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

We sometimes feature the work done by the community on our website. If you would like your GitHub user excluded from that, please email tal@dav.network

**Comment by arshadkazmi42** [comment]
Taking this up.

**Comment by summerteeth** [comment]
@TalAter very interesting project. I would love to do that.

**Comment by glazey132** [comment]
Hi DavFoundation team!

Sounds like you guys are doing some pretty awesome things and I would love to help you guys with this issue.

Can I stake a claim on this? This would be my first contribution to open source.

**Comment by devansh289** [comment]
I am a first-time. This project looks amazing and would love to work on this.

**Comment by pranav1698** [comment]
Hi DavFoundationTeam,
I am a first timer and would like to help you with this issue

**Comment by TalAter** [comment]
Thank you @pranav1698 🎆 

I hope this is the first of many contributions to the open source community from you 😄

**Comment by pranav1698** [comment]
Sure, I had fun working on it
